name: my_currency

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: my_currency-web
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src/
    env_file:
      - ../envs/local/web.env
    depends_on:
      - postgres-db
    command: ["uv", "run", "uvicorn", "my_currency.asgi:application", "--host", "0.0.0.0", "--reload"]

  postgres-db:
    image: postgres:18.1-alpine
    restart: unless-stopped
    env_file:
      - ../envs/local/postgres_db.env
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data/

volumes:
  profile_postgres_data:
